---
- hosts: all
  name: Setup initial configuration

  pre_tasks:

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
        state: present

    - name: Start qemu-guest-agent service
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true

    - name: Install gpg
      ansible.builtin.apt:
        name: gnupg
        state: present

- hosts: all
  name: Install and configure system utilities
  roles:
    - zram

- hosts: snowflake
  name: Install snowflake
  roles:
    - snowflake

- hosts: webtunnel
  name: Install webtunnel
  roles:
    - webtunnel

- hosts: obfs4
  name: Install obfs4
  roles:
    - obfs4

- hosts: meek
  name: Install meek
  roles:
    - meek
